src/Entity/BuildEnvironmentInterface.php
<?php

namespace Drupal\build_trigger\Entity;

use Drupal\build_trigger\BuildEnvironmentPluginInterface;
use Drupal\Core\Config\Entity\ConfigEntityInterface;

/**
 * Provides an interface defining a build environment entity type.
 */
interface BuildEnvironmentInterface extends ConfigEntityInterface {

  /**
   * Trigger build job.
   *
   * @param \Drupal\build_trigger\Entity\BuildJob $build_job
   *   The build job to update for the build.
   */
  public function build(BuildJob $build_job);

  /**
   * Get the colour for the environment.
   *
   * @return string
   *   The colour.
   */
  public function getColour(): string;

  /**
   * Gets the build environment plugin for this environment.
   *
   * @return \Drupal\build_trigger\BuildEnvironmentPluginInterface
   *   The build environment plugin.
   */
  public function getPlugin(): BuildEnvironmentPluginInterface;

  /**
   * Get the URL of the environment.
   *
   * @return string
   *   The environment URL.
   */
  public function getUrl(): string;

  /**
   * Get the weight of the environment.
   *
   * @return int
   *   The environment weight.
   */
  public function getWeight(): int;

}

templates/build-job.html.twig
{#
/**
 * @file
 * Default theme implementation to display a build job.
 *
 * Available variables:
 * - active: Active flag.
 * - build_job: The build_job entity.
 * - changed: Last updated date.
 * - created: Created date.
 * - details: Build details.
 * - environment: The environment plugin associated with the build job.
 * - owner: Name if user who startedf the build.
 * - plugin: The plugin used by the environment.
 * - status: Current status code for the build job.
 *
 * @see template_preprocess_build_job()
 *
 * @ingroup themeable
 */
#}

{{ attach_library('build_trigger/build_job') }}

{% if active %}
   <a href="{{ path('build_trigger.build_job_update', {'build_job': build_job.id()}) }}" class="button button--primary">Refresh build status</a>
{% endif %}

<table>
  <tr>
    <th scope="row">Status</th>
    <td>{{ status|capitalize }}</td>
  </tr>
  <tr>
    <th scope="row">Environment</th>
    <td><a href="{{ environment.url }}">{{ environment.label }}</a></td>
  </tr>
  <tr>
    <th scope="row">Type</th>
    <td>{{ plugin.pluginDefinition.label }}</a></td>
  </tr>
  <tr>
    <th scope="row">Started by</th>
    <td>{{ owner }}</td>
  </tr>
  <tr>
    <th scope="row">Created</th>
    <td>{{ created|date('Y-m-d H:i:s') }}</td>
  </tr>
  <tr>
    <th scope="row">Updated</th>
    <td>{{ changed|date('Y-m-d H:i:s') }}</td>
  </tr>
</table>

{% if details %}
  {{ details }}
{% endif %}